<?php
require_once __DIR__ . '/config.php';

$javaDir = __DIR__ . '/java';
$classFile = $javaDir . '/AssignmentReport.class';
$sourceFile = $javaDir . '/AssignmentReport.java';

$output = '';
$errorMsg = '';

// Compile if needed
if (!file_exists($classFile)) {
    exec('javac ' . escapeshellarg($sourceFile) . ' 2>&1', $compileOut, $compileCode);
    if ($compileCode !== 0) {
        $errorMsg = "Compilation failed:\n" . implode("\n", $compileOut);
    }
}

if (!$errorMsg) {
    $cmd = sprintf(
        'cd %s && java AssignmentReport %s 2>&1',
        escapeshellarg($javaDir),
        escapeshellarg(DATA_FILE)
    );
    exec($cmd, $runOut, $runCode);
    $output = implode("\n", $runOut);
    if ($runCode !== 0 && !$output) {
        $errorMsg = 'Java process failed to run. Is a JDK installed on this server?';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Assignment Report</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<div class="wrap">
    <header>
        <h1>Summary Report</h1>
        <p class="sub">Generated by the Java reporting tool</p>
    </header>

    <section class="card">
        <?php if ($errorMsg): ?>
            <div class="notice err"><?= nl2br(htmlspecialchars($errorMsg)) ?></div>
        <?php else: ?>
            <pre class="report"><?= htmlspecialchars($output) ?></pre>
        <?php endif; ?>
        <a class="back" href="index.php">&larr; Back to assignments</a>
    </section>
</div>
</body>
</html>
